```{r}
#初始化
rm(list=ls())
setwd("C:/Users/Lenovo/Code/R/ARIMA")
#导入数据 划分训练集测试集
data=ts(read.csv("data.csv",head=T),start=2017,freq=244)
data=ts(data,start=c(2017,1),end=c(2018,10),freq=244)
train=ts(data,start=c(2017,1),end=c(2017,244),freq=244)
test=ts(data[245:255],start=c(2018,1),end=c(2018,10),freq=244)
plot(data,col=1,main="data")
lines(test,col=2)
legend("topright",c("train","test"),lty=1,col=c(1,2))
```




```{r}
#画出自相关函数图
library("astsa")
acf(train)
```

```{r}
#在对上述数据进行差分后，画原始图，自相关系数，偏自相关系数图
data.diff=diff(train)
plot(data.diff)
acf(data.diff)
pacf(data.diff)
```

```{r}
#使用ARIMA模型进行拟合
ma.fit=sarima(train,0,1,1,details=T)
ma.fit
```

```{r}
#预测结果 最后五十个
predict=sarima.for(train,10,0,1,1)$pred
```

```{r}
#上面那个图是自动生成的，不好看，用下面这个
plot(data,col=1,main="predict")
lines(test,col=2)
lines(predict,col=4)
legend("topright",c("train","test","predict"),lty=1,col=c(1,2,4))
```
```{r}
#RMSE均方根误差 在预测集上
#MAE平均绝对误差
RMSE=(sum((test-predict)^2)/length(predict))^0.5
MAE=sum(abs(test-predict))/length(predict)
MAPE=sum(abs(test-predict)/test)/length(predict)*100
RMSE
MAE
MAPE
```
